### ISSUE TITLE
ManagedCertificate

### ISSUE THREAD

**Issue by Tensho** [GoogleCloudPlatform/gke-gateway-api#19]
Do you have any insight into when GKE Gateway API will support `ManagedCertificate` CRD similar to [GKE Ingress](https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs#creating_an_ingress_with_a_google-managed_certificate)? We plan to have a cluster shared Gateway across many namespaces and create SSL cert for each of them out of band with `pre-shared-cert` [GKE Gateway](https://cloud.google.com/kubernetes-engine/docs/how-to/secure-gateway#secure-using-ssl-certificate) annotation doesn't encourage us to move forward. Ideally, we'd like the GKE Gateway controller to infer a managed SSL certificate from the `HTTPRoute` hostnames without declaring the `ManagedCertificate` manifest at all.

**Comment by briantkennedy** [comment]
Hi @Tensho, we have this on our backlog, but it's not presently scheduled, so I can't give you a firm date for when this will be available.  I'll link our internal issue tracker to this issue.  Also, if you can provide more details about the workflow the provisioning is used in and higher level goals of what this accomplishes, it will help us get a better picture of what the API surface should look like.

Thanks,
Brian

**Comment by Tensho** [comment]
@briantkennedy Thanks for checking this in your backlog 🙇‍♂️ I've already found a way to provision SSL certificates based on `hostnames` attribute of `HTTPRoute` resource automatically ([Secure a Gateway using Certificate Manager](https://cloud.google.com/kubernetes-engine/docs/how-to/secure-gateway#secure-using-certificate-manager)). That's exactly what we've been looking initially. This approach allows provisioning SSL certificates and link them to Gateway GLB **implicitly**.
